// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  THREE.AnimationSetFrameProcessor = (function() {
    function AnimationSetFrameProcessor() {}

    AnimationSetFrameProcessor.prototype.process = function(frame, onLoad, onProgress, onError) {
      var worker;
      worker = new Worker('/uploads/apps/mesh_viewer/classes/animationsetframeprocessor-worker.js');
      worker.onmessage = (function(_this) {
        return function(message) {
          var buffers, geometry;
          switch (message.data.type) {
            case 'progress':
              if (onProgress) {
                return onProgress(message.data.loadPercentage);
              }
              break;
            case 'result':
              if (onProgress) {
                onProgress(100);
              }
              buffers = message.data.buffers;
              geometry = new THREE.BufferGeometry();
              geometry.addAttribute('position', new THREE.BufferAttribute(buffers.positions, 3));
              geometry.addAttribute('color', new THREE.BufferAttribute(buffers.colors, 3));
              geometry.setIndex(new THREE.BufferAttribute(buffers.indices, 1));
              geometry.computeVertexNormals();
              geometry.computeBoundingSphere();
              geometry.computeBoundingBox();
              return onLoad(geometry);
          }
        };
      })(this);
      return worker.postMessage({
        frame: frame
      });
    };

    return AnimationSetFrameProcessor;

  })();

}).call(this);

//# sourceMappingURL=animationsetframeprocessor.js.map
