// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  TopViewer.Animation = (function() {
    function Animation() {
      this.frameTimes = [];
    }

    Animation.prototype.addFrameTime = function(time) {
      return this.addFrameTimes([time]);
    };

    Animation.prototype.addFrameTimes = function(times) {
      this.frameTimes = _.union(this.frameTimes, times);
      return this.frameTimes.sort(function(a, b) {
        return a - b;
      });
    };

    return Animation;

  })();

}).call(this);

//# sourceMappingURL=animation.js.map
