// Generated by CoffeeScript 1.10.0
(function() {
  TopViewer.File = (function() {
    File.loaders = {
      ply: new TopViewer.PLYLoader,
      hive: new TopViewer.HiveLoader,
      top: new TopViewer.TopLoader
    };

    function File(url) {
      this.url = url;
      this.extension = this.url.split('.').pop();
      this.loader = this.constructor.loaders[this.extension];
    }

    File.prototype.load = function(onCompleteHandler) {
      return this.loader.load(this.url, (function(_this) {
        return function(objects) {
          _this.objects = objects;
          return onCompleteHandler();
        };
      })(this));
    };

    return File;

  })();

}).call(this);

//# sourceMappingURL=file.js.map
