// Generated by CoffeeScript 1.10.0
(function() {
  TopViewer.File = (function() {
    File.loaders = {
      ply: new TopViewer.PLYLoader,
      hive: new TopViewer.HiveLoader,
      top: new TopViewer.TopLoader
    };

    File.loaders.xpost = File.loaders.top;

    function File(url) {
      this.url = url;
      this.extension = this.url.split('.').pop();
      this.loader = this.constructor.loaders[this.extension];
    }

    File.prototype.load = function(onCompleteHandler) {
      if (!this.loader) {
        setTimeout((function(_this) {
          return function() {
            _this.objects = {};
            return onCompleteHandler();
          };
        })(this), 0);
        return;
      }
      return this.loader.load(this.url, (function(_this) {
        return function(objects) {
          _this.objects = objects;
          return onCompleteHandler();
        };
      })(this), (function(_this) {
        return function(loadPercentage) {};
      })(this));
    };

    return File;

  })();

}).call(this);

//# sourceMappingURL=file.js.map
