// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  TopViewer.Gradient = (function() {
    function Gradient(name, url) {
      this.name = name;
      this.url = url;
      this.data = new Uint8Array(1024 * 4);
      this.texture = new THREE.DataTexture(this.data, 1024, 1, THREE.RGBAFormat, THREE.UnsignedByteType);
      this.image = new Image();
      this.image.onload = (function(_this) {
        return function() {
          var canvas, i, j, ref, uintData;
          canvas = document.createElement('canvas');
          canvas.width = 1024;
          canvas.height = 1;
          canvas.getContext('2d').drawImage(_this.image, 0, 0, 1024, 1);
          uintData = canvas.getContext('2d').getImageData(0, 0, 1024, 1).data;
          for (i = j = 0, ref = uintData.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
            _this.data[i] = uintData[i];
          }
          return _this.texture.needsUpdate = true;
        };
      })(this);
      this.image.src = this.url;
    }

    Gradient.prototype.colorAtPercentage = function(percentage) {
      var index, pixelIndex;
      pixelIndex = Math.floor(1024 * percentage);
      pixelIndex = Math.max(0, Math.min(1023, pixelIndex));
      index = pixelIndex * 4;
      return {
        r: this.data[index],
        g: this.data[index + 1],
        b: this.data[index + 2],
        a: this.data[index + 3]
      };
    };

    return Gradient;

  })();

}).call(this);

//# sourceMappingURL=gradient.js.map
