// Generated by CoffeeScript 1.10.0
(function() {
  window.TopViewer = (function() {
    function TopViewer() {}

    return TopViewer;

  })();

}).call(this);

//# sourceMappingURL=namespace.js.map
