// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  TopViewer.PLYLoader = (function() {
    function PLYLoader() {}

    PLYLoader.prototype.load = function(url, onLoad, onProgress, onError) {
      var worker;
      worker = new Worker('/uploads/apps/top_viewer/classes/plyloader-worker.js');
      worker.onmessage = (function(_this) {
        return function(message) {
          var buffers, geometry;
          switch (message.data.type) {
            case 'progress':
              if (onProgress) {
                return onProgress(message.data.loadPercentage);
              }
              break;
            case 'result':
              if (onProgress) {
                onProgress(100);
              }
              buffers = message.data.buffers;
              geometry = new THREE.BufferGeometry();
              if (buffers.positions) {
                geometry.addAttribute('position', new THREE.BufferAttribute(buffers.positions, 3));
              }
              if (buffers.normals) {
                geometry.addAttribute('normal', new THREE.BufferAttribute(buffers.normals, 3));
              }
              if (buffers.colors) {
                geometry.addAttribute('color', new THREE.BufferAttribute(buffers.colors, 3));
              }
              if (buffers.indices) {
                geometry.setIndex(new THREE.BufferAttribute(buffers.indices, 1));
              }
              geometry.computeBoundingSphere();
              geometry.computeBoundingBox();
              return onLoad(geometry);
          }
        };
      })(this);
      return worker.postMessage({
        url: url,
        propertyNameMapping: this.propertyNameMapping
      });
    };

    return PLYLoader;

  })();

}).call(this);

//# sourceMappingURL=plyloader.js.map
