// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  TopViewer.RenderingControls = (function(superClass) {
    extend(RenderingControls, superClass);

    RenderingControls.MeshSurfaceSides = {
      SingleFront: 'SingleFront',
      SingleBack: 'SingleBack',
      DoubleFast: 'DoubleFast',
      DoubleQuality: 'DoubleQuality'
    };

    RenderingControls.VertexColorsType = {
      Color: 'Color',
      Scalar: 'Scalar'
    };

    function RenderingControls(options) {
      var $gradientArea, $gradientPreview, $lightingArea, $meshesArea, $meshesIsolinesArea, $meshesSurfaceArea, $meshesWireframeArea, $volumesArea, $volumesIsosurfacesArea, $volumesWireframeArea, applyScrollOffset, customLight, found, gradient, gradientPreviewImage, i, j, len, len1, lightingPreset, ref, ref1, saveState, scrollOffset;
      this.options = options;
      RenderingControls.__super__.constructor.apply(this, arguments);
      saveState = this.options.engine.options.app.state.renderingControls;
      this.$appWindow = this.options.engine.$appWindow;
      this.scene = this.options.engine.scene;
      this.$controls = $("<div class='rendering-controls'>");
      this.$appWindow.append(this.$controls);
      this.$rootElement = this.$controls;
      this.rootControl = new TopViewer.UIControl(this, this.$controls);
      this._syncHandlers = [];
      console.log("got soff", saveState.scrollOffset);
      scrollOffset = saveState.scrollOffset || 0;
      applyScrollOffset = (function(_this) {
        return function() {
          return _this.$controls.css({
            top: -scrollOffset
          });
        };
      })(this);
      setTimeout((function(_this) {
        return function() {
          return applyScrollOffset();
        };
      })(this), 1);
      this.rootControl.scroll((function(_this) {
        return function(delta) {
          scrollOffset += delta;
          scrollOffset = Math.max(scrollOffset, 0);
          scrollOffset = Math.min(scrollOffset, _this.$controls.height() - _this.options.engine.$appWindow.height() * 0.8);
          saveState.scrollOffset = scrollOffset;
          return applyScrollOffset();
        };
      })(this));
      this._onSync((function(_this) {
        return function(data) {
          scrollOffset = data.scrollOffset;
          return applyScrollOffset();
        };
      })(this));
      $lightingArea = $("<div class='lighting-area'></div>");
      new TopViewer.ToggleContainer(this, {
        $parent: this.$controls,
        text: "Lighting",
        "class": "panel",
        visible: saveState.lighting.panelEnabled,
        $contents: $lightingArea,
        onChange: (function(_this) {
          return function(value) {
            return saveState.lighting.panelEnabled = value;
          };
        })(this)
      });
      this.lightingSetupControl = new TopViewer.DropdownControl(this, {
        $parent: $lightingArea,
        "class": 'lighting-setup-dropdown',
        onChange: (function(_this) {
          return function(value, control) {
            return saveState.lighting.lightingSetup = {
              name: control.dropdownControl.options.text,
              value: value.lightDirection
            };
          };
        })(this)
      });
      ref = this.options.engine.lightingPresets;
      for (i = 0, len = ref.length; i < len; i++) {
        lightingPreset = ref[i];
        this.lightingSetupControl.addValue(lightingPreset.name, lightingPreset);
      }
      if (saveState.lighting.lightingSetup.name) {
        found = this.lightingSetupControl.setValue(saveState.lighting.lightingSetup.name);
        if (!found) {
          customLight = new LightingSetup(saveState.lightingSetup.name, saveState.lightingSetup.value);
          this.lightingSetupControl.setValueDirectly(customLight.name, customLight);
        }
      } else {
        this.lightingSetupControl.setValue(this.options.engine.lightingPresets[0]);
      }
      this.bidirectionalLightControl = new TopViewer.CheckboxControl(this, {
        $parent: $lightingArea,
        name: 'Bidirectional',
        value: saveState.lighting.bidirectional,
        onChange: (function(_this) {
          return function(value) {
            return saveState.lighting.bidirectional = value;
          };
        })(this)
      });
      this.shadowsControl = new TopViewer.CheckboxControl(this, {
        $parent: $lightingArea,
        name: 'Cast shadows',
        value: saveState.lighting.shadows,
        onChange: (function(_this) {
          return function(value) {
            return saveState.lighting.shadows = value;
          };
        })(this)
      });
      $lightingArea.append("<p class='label'>Ambient light</p>");
      this.ambientLevelControl = new TopViewer.SliderControl(this, {
        $parent: $lightingArea,
        minimumValue: 0,
        maximumValue: 1,
        value: saveState.lighting.ambient,
        decimals: -2,
        onChange: (function(_this) {
          return function(value) {
            return saveState.lighting.ambient = value;
          };
        })(this)
      });
      $gradientArea = $("<div class='gradient-area'></div>");
      new TopViewer.ToggleContainer(this, {
        $parent: this.$controls,
        text: "Colors",
        "class": "panel",
        visible: saveState.gradient.panelEnabled,
        $contents: $gradientArea,
        onChange: (function(_this) {
          return function(value) {
            return saveState.gradient.panelEnabled = value;
          };
        })(this)
      });
      $gradientPreview = $("<div class='gradient-preview-area'><img class='gradient-preview-image'/></div>");
      gradientPreviewImage = $gradientPreview.find('img')[0];
      this.gradientControl = new TopViewer.DropdownControl(this, {
        $parent: $gradientArea,
        "class": 'gradient-dropdown',
        onChange: (function(_this) {
          return function(value) {
            gradientPreviewImage.src = value.url;
            saveState.gradient.name = value.name;
            return TopViewer.CurveTransformControl.drawSpectrogram();
          };
        })(this)
      });
      ref1 = this.options.engine.gradients;
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        gradient = ref1[j];
        this.gradientControl.addValue(gradient.name, gradient);
      }
      found = false;
      if (saveState.gradient.name) {
        found = this.gradientControl.setValue(saveState.gradient.name);
      }
      if (!found) {
        this.gradientControl.setValue(this.options.engine.gradients[0]);
      }
      $gradientArea.append($gradientPreview);
      $meshesArea = $("<div class='meshes-area'></div>");
      new TopViewer.ToggleContainer(this, {
        $parent: this.$controls,
        text: "Meshes",
        "class": "panel",
        visible: saveState.meshes.panelEnabled,
        $contents: $meshesArea,
        onChange: (function(_this) {
          return function(value) {
            return saveState.meshes.panelEnabled = value;
          };
        })(this)
      });
      $meshesSurfaceArea = $("<div class='surface-area sub-panel first'><div class='title'>Surface</div></div>");
      $meshesArea.append($meshesSurfaceArea);
      this.meshesShowSurfaceControl = new TopViewer.CheckboxControl(this, {
        $parent: $meshesSurfaceArea,
        name: 'Enable',
        value: saveState.meshes.surfaceEnabled,
        onChange: (function(_this) {
          return function(value) {
            return saveState.meshes.surfaceEnabled = value;
          };
        })(this)
      });
      this.meshesSurfaceSidesControl = new TopViewer.DropdownControl(this, {
        $parent: $meshesSurfaceArea,
        "class": 'meshes-surface-sides-selector',
        onChange: (function(_this) {
          return function(value) {
            return saveState.meshes.surfaceSides = value;
          };
        })(this)
      });
      this.meshesSurfaceSidesControl.addValue('Single Sided (front)', this.constructor.MeshSurfaceSides.SingleFront);
      this.meshesSurfaceSidesControl.addValue('Single Sided (back)', this.constructor.MeshSurfaceSides.SingleBack);
      this.meshesSurfaceSidesControl.addValue('Double Sided (fast)', this.constructor.MeshSurfaceSides.DoubleFast);
      this.meshesSurfaceSidesControl.addValue('Double Sided (quality)', this.constructor.MeshSurfaceSides.DoubleQuality);
      this.meshesSurfaceSidesControl.setValue(saveState.meshes.surfaceSides);
      this.meshesSurfaceColorsControl = new TopViewer.VertexColorsControl(this, {
        $parent: $meshesSurfaceArea,
        "class": 'meshes-surface-colors-selector',
        saveState: saveState.meshes.surfaceColors
      });
      $meshesSurfaceArea.append("<p class='label'>Opacity</p>");
      this.meshesSurfaceOpacityControl = new TopViewer.SliderControl(this, {
        $parent: $meshesSurfaceArea,
        minimumValue: 0,
        maximumValue: 1,
        value: saveState.meshes.surfaceOpacity,
        decimals: -2,
        onChange: (function(_this) {
          return function(value) {
            return saveState.meshes.surfaceOpacity = value;
          };
        })(this)
      });
      $meshesWireframeArea = $("<div class='wireframe-area sub-panel'><div class='title'>Wireframe</div></div>");
      $meshesArea.append($meshesWireframeArea);
      this.meshesShowWireframeControl = new TopViewer.CheckboxControl(this, {
        $parent: $meshesWireframeArea,
        name: 'Enable',
        value: saveState.meshes.wireframeEnabled,
        onChange: (function(_this) {
          return function(value) {
            return saveState.meshes.wireframeEnabled = value;
          };
        })(this)
      });
      this.meshesWireframeColorsControl = new TopViewer.VertexColorsControl(this, {
        $parent: $meshesWireframeArea,
        "class": 'meshes-wireframe-colors-selector',
        saveState: saveState.meshes.wireframeColors
      });
      $meshesWireframeArea.append("<p class='label'>Opacity</p>");
      this.meshesWireframeOpacityControl = new TopViewer.SliderControl(this, {
        $parent: $meshesWireframeArea,
        minimumValue: 0,
        maximumValue: 1,
        value: saveState.meshes.wireframeOpacity,
        decimals: -2,
        onChange: (function(_this) {
          return function(value) {
            return saveState.meshes.wireframeOpacity = value;
          };
        })(this)
      });
      $meshesIsolinesArea = $("<div class='isolines-area sub-panel'><div class='title'>Isolines</div></div>");
      $meshesArea.append($meshesIsolinesArea);
      this.meshesShowIsolinesControl = new TopViewer.CheckboxControl(this, {
        $parent: $meshesIsolinesArea,
        name: 'Enable',
        value: saveState.meshes.isolinesEnabled,
        onChange: (function(_this) {
          return function(value) {
            return saveState.meshes.isolinesEnabled = value;
          };
        })(this)
      });
      this.meshesIsolinesScalarControl = new TopViewer.ScalarControl(this, {
        $parent: $meshesIsolinesArea,
        saveState: saveState.meshes.isolinesScalar
      });
      this.meshesIsolinesColorsControl = new TopViewer.VertexColorsControl(this, {
        $parent: $meshesIsolinesArea,
        "class": 'meshes-isolines-colors-selector',
        saveState: saveState.meshes.isolinesColors
      });
      $meshesIsolinesArea.append("<p class='label'>Opacity</p>");
      this.meshesIsolinesOpacityControl = new TopViewer.SliderControl(this, {
        $parent: $meshesIsolinesArea,
        minimumValue: 0,
        maximumValue: 1,
        value: saveState.meshes.isolinesOpacity,
        decimals: -2,
        onChange: (function(_this) {
          return function(value) {
            return saveState.meshes.isolinesOpacity = value;
          };
        })(this)
      });
      this.$meshes = $("<ul class='meshes sub-panel'></ul>");
      $meshesArea.append(this.$meshes);
      $volumesArea = $("<div class='volumes-area'></div>");
      new TopViewer.ToggleContainer(this, {
        $parent: this.$controls,
        text: "Volumes",
        "class": "panel",
        visible: saveState.volumes.panelEnabled,
        $contents: $volumesArea,
        onChange: (function(_this) {
          return function(value) {
            return saveState.volumes.panelEnabled = value;
          };
        })(this)
      });
      $volumesWireframeArea = $("<div class='wireframe-area sub-panel'><div class='title'>Wireframe</div></div>");
      $volumesArea.append($volumesWireframeArea);
      this.volumesShowWireframeControl = new TopViewer.CheckboxControl(this, {
        $parent: $volumesWireframeArea,
        name: 'Enable',
        value: saveState.volumes.wireframeEnabled,
        onChange: (function(_this) {
          return function(value) {
            return saveState.volumes.wireframeEnabled = value;
          };
        })(this)
      });
      this.volumesWireframeColorsControl = new TopViewer.VertexColorsControl(this, {
        $parent: $volumesWireframeArea,
        "class": 'volumes-wireframe-colors-selector',
        saveState: saveState.volumes.wireframeColors
      });
      $volumesWireframeArea.append("<p class='label'>Opacity</p>");
      this.volumesWireframeOpacityControl = new TopViewer.SliderControl(this, {
        $parent: $volumesWireframeArea,
        minimumValue: 0,
        maximumValue: 1,
        value: saveState.volumes.wireframeOpacity,
        decimals: -2,
        onChange: (function(_this) {
          return function(value) {
            return saveState.volumes.wireframeOpacity = value;
          };
        })(this)
      });
      $volumesIsosurfacesArea = $("<div class='isosrufaces-area sub-panel'><div class='title'>Isosurfaces</div></div>");
      $volumesArea.append($volumesIsosurfacesArea);
      this.volumesShowIsosurfacesControl = new TopViewer.CheckboxControl(this, {
        $parent: $volumesIsosurfacesArea,
        name: 'Enable',
        value: saveState.volumes.isosurfacesEnabled,
        onChange: (function(_this) {
          return function(value) {
            return saveState.volumes.isosurfacesEnabled = value;
          };
        })(this)
      });
      this.volumesIsosurfacesScalarControl = new TopViewer.ScalarControl(this, {
        $parent: $volumesIsosurfacesArea,
        saveState: saveState.volumes.isosurfacesScalar
      });
      this.volumesIsosurfacesColorsControl = new TopViewer.VertexColorsControl(this, {
        $parent: $volumesIsosurfacesArea,
        "class": 'volumes-isosurfaces-colors-selector',
        saveState: saveState.volumes.isosurfacesColors
      });
      $volumesIsosurfacesArea.append("<p class='label'>Opacity</p>");
      this.volumesIsosurfacesOpacityControl = new TopViewer.SliderControl(this, {
        $parent: $volumesIsosurfacesArea,
        minimumValue: 0,
        maximumValue: 1,
        value: saveState.volumes.isosurfacesOpacity,
        decimals: -2,
        onChange: (function(_this) {
          return function(value) {
            return saveState.volumes.isosurfacesOpacity = value;
          };
        })(this)
      });
      this.$scalarsArea = $("<ul class='scalars-area'></ul>");
      new TopViewer.ToggleContainer(this, {
        $parent: this.$controls,
        text: "Scalars",
        "class": "panel",
        visible: saveState.scalars.panelEnabled,
        $contents: this.$scalarsArea,
        onChange: (function(_this) {
          return function(value) {
            return saveState.scalars.panelEnabled = value;
          };
        })(this)
      });
      this.$vectorsArea = $("<div class='vectors-area'></div>");
      new TopViewer.ToggleContainer(this, {
        $parent: this.$controls,
        text: "Vectors",
        "class": "panel",
        visible: saveState.vectors.panelEnabled,
        $contents: this.$vectorsArea,
        onChange: (function(_this) {
          return function(value) {
            return saveState.vectors.panelEnabled = value;
          };
        })(this)
      });
      this.$vectorsDisplacementArea = $("<div class='vectors-displacement-area sub-panel'><div class='title'>Displacement</div></div>");
      this.$vectorsArea.append(this.$vectorsDisplacementArea);
      this.vectorsDisplacementVectorControl = new TopViewer.VectorControl(this, {
        $parent: this.$vectorsDisplacementArea,
        saveState: saveState.vectors.displacementVector
      });
      this.$vectorsDisplacementArea.append("<p class='label'>Amplification</p>");
      this.vectorsDisplacementFactorControl = new TopViewer.SliderControl(this, {
        $parent: this.$vectorsDisplacementArea,
        "class": 'vectors-displacement-factor',
        minimumValue: 0,
        maximumValue: 100,
        power: 4,
        decimals: -2,
        value: saveState.vectors.displacementFactor,
        onChange: (function(_this) {
          return function(value) {
            return saveState.displacementFactor = value;
          };
        })(this)
      });
      this.$vectorsFieldArea = $("<div class='vectors-field-area sub-panel'><div class='title'>Vector field</div></div>");
      this.$vectorsArea.append(this.$vectorsFieldArea);
      this.vectorsFieldVectorControl = new TopViewer.VectorControl(this, {
        $parent: this.$vectorsFieldArea,
        saveState: saveState.vectors.fieldVector
      });
      this.$vectorsFieldArea.append("<p class='label'>Unit length</p>");
      this.vectorsFieldLengthControl = new TopViewer.SliderControl(this, {
        $parent: this.$vectorsFieldArea,
        "class": 'vectors-field-length',
        minimumValue: 0,
        maximumValue: 2,
        power: 4,
        decimals: -4,
        value: saveState.vectors.fieldLength,
        onChange: (function(_this) {
          return function(value) {
            return saveState.vectors.fieldLength = value;
          };
        })(this)
      });
      this.vectorsFieldColorsControl = new TopViewer.VertexColorsControl(this, {
        $parent: this.$vectorsFieldArea,
        "class": 'vectors-field-colors-selector',
        saveState: saveState.vectors.fieldColors
      });
      this.$vectorsFieldArea.append("<p class='label'>Opacity</p>");
      this.vectorsFieldOpacityControl = new TopViewer.SliderControl(this, {
        $parent: this.$vectorsFieldArea,
        minimumValue: 0,
        maximumValue: 1,
        value: saveState.vectors.fieldOpacity,
        decimals: -2,
        onChange: (function(_this) {
          return function(value) {
            return saveState.vectors.fieldOpacity = value;
          };
        })(this)
      });
      this.initialize();
    }

    RenderingControls.prototype.addMesh = function(name, mesh) {
      var $contents, $mesh, saveState, states;
      $mesh = $("<li class='mesh'></li>");
      this.$meshes.append($mesh);
      $contents = $("<div>");
      states = this.options.engine.options.app.state.renderingControls.meshes;
      saveState = TopViewer.SaveState.findStateForName(states, name);
      mesh.renderingControls = {
        showSurfaceControl: new TopViewer.CheckboxControl(this, {
          $parent: $contents,
          name: 'surface',
          parent: this.meshesShowSurfaceControl,
          value: saveState.surfaceEnabled,
          onChange: function(value) {
            return saveState.surfaceEnabled = value;
          }
        }),
        showWireframeControl: new TopViewer.CheckboxControl(this, {
          $parent: $contents,
          name: 'wireframe',
          parent: this.meshesShowWireframeControl,
          value: saveState.wireframeEnabled,
          onChange: function(value) {
            return saveState.wireframeEnabled = value;
          }
        }),
        showIsolinesControl: new TopViewer.CheckboxControl(this, {
          $parent: $contents,
          name: 'isolines',
          parent: this.meshesShowIsolinesControl,
          value: saveState.isolinesEnabled,
          onChange: function(value) {
            return saveState.isolinesEnabled = value;
          }
        })
      };
      return new TopViewer.ToggleContainer(this, {
        $parent: $mesh,
        text: name,
        visible: false,
        $contents: $contents
      });
    };

    RenderingControls.prototype.addVolume = function(name, mesh) {
      var $contents, $mesh;
      $mesh = $("<li class='mesh'></li>");
      this.$meshes.append($mesh);
      $contents = $("<div>");
      mesh.renderingControls = {
        wireframe: new TopViewer.CheckboxControl(this, {
          $parent: $contents,
          name: 'wireframe',
          value: false
        }),
        isosurfaces: new TopViewer.CheckboxControl(this, {
          $parent: $contents,
          name: 'isosurfaces',
          value: true
        })
      };
      return new TopViewer.ToggleContainer(this, {
        $parent: $mesh,
        text: name,
        visible: false,
        $contents: $contents
      });
    };

    RenderingControls.prototype.addScalar = function(name, scalar) {
      var $contents, $scalar, states;
      TopViewer.ScalarControl.addResults(name, scalar);
      $scalar = $("<li class='scalar'></li>");
      this.$scalarsArea.append($scalar);
      $contents = $("<div>");
      new TopViewer.ToggleContainer(this, {
        $parent: $scalar,
        text: name,
        visible: true,
        $contents: $contents
      });
      states = this.options.engine.options.app.state.renderingControls.scalars;
      return scalar.renderingControls = {
        curveTransformControl: new TopViewer.CurveTransformControl(this, {
          $parent: $contents,
          saveState: TopViewer.SaveState.findStateForName(states, name),
          scalar: scalar,
          gradientControl: this.gradientControl
        })
      };
    };

    RenderingControls.prototype.addVector = function(name, vector) {
      return TopViewer.VectorControl.addResults(name, vector);
    };

    RenderingControls.prototype.onMouseDown = function(position, button) {
      RenderingControls.__super__.onMouseDown.apply(this, arguments);
      return TopViewer.CurveTransformControl.mouseDown(this.transformPositionToPage(position));
    };

    RenderingControls.prototype.onMouseMove = function(position) {
      RenderingControls.__super__.onMouseMove.apply(this, arguments);
      return TopViewer.CurveTransformControl.mouseMove(this.transformPositionToPage(position));
    };

    RenderingControls.prototype.onMouseUp = function(position, button) {
      RenderingControls.__super__.onMouseUp.apply(this, arguments);
      return TopViewer.CurveTransformControl.mouseUp(this.transformPositionToPage(position));
    };

    RenderingControls.prototype.transformPositionToPage = function(position) {
      var offset;
      offset = this.$appWindow.offset();
      return {
        x: position.x + offset.left,
        y: position.y + offset.top
      };
    };

    RenderingControls.prototype.sync = function(data) {
      var handler, i, len, ref, results;
      ref = this._syncHandlers;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        handler = ref[i];
        results.push(handler(data));
      }
      return results;
    };

    RenderingControls.prototype._onSync = function(handler) {
      return this._syncHandlers.push(handler);
    };

    return RenderingControls;

  })(TopViewer.UIArea);

}).call(this);

//# sourceMappingURL=renderingcontrols.js.map
