// Generated by CoffeeScript 1.10.0
(function() {
  var maxStates;

  maxStates = 5;

  TopViewer.SaveState = (function() {
    function SaveState() {}

    SaveState.findStateForName = function(states, name) {
      var firstFreeIndex, i, j, ref;
      firstFreeIndex = 0;
      for (i = j = 0, ref = maxStates; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        if (states[i].name === name) {
          return states[i].state;
        }
        if (!states[i].name) {
          break;
        }
        firstFreeIndex++;
      }
      if (!(firstFreeIndex < maxStates)) {
        return null;
      }
      states[firstFreeIndex].name = name;
      return states[firstFreeIndex].state;
    };

    return SaveState;

  })();

}).call(this);

//# sourceMappingURL=savestate.js.map
