// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  TopViewer.TopLoader = (function() {
    function TopLoader() {}

    TopLoader.prototype.load = function(options) {
      var worker;
      worker = new Worker('/uploads/apps/top_viewer/classes/toploader-worker.js');
      worker.onmessage = (function(_this) {
        return function(message) {
          switch (message.data.type) {
            case 'size':
              return typeof options.onSize === "function" ? options.onSize(message.data.size) : void 0;
            case 'progress':
              return typeof options.onProgress === "function" ? options.onProgress(message.data.loadPercentage) : void 0;
            case 'result':
              return typeof options.onResults === "function" ? options.onResults(message.data.objects) : void 0;
            case 'complete':
              return typeof options.onComplete === "function" ? options.onComplete() : void 0;
          }
        };
      })(this);
      return worker.postMessage({
        url: options.url
      });
    };

    return TopLoader;

  })();

}).call(this);

//# sourceMappingURL=toploader.js.map
