// Generated by CoffeeScript 1.10.0
(function() {
  TopViewer.CheckboxControl = (function() {
    function CheckboxControl(uiArea, options) {
      var valueControl;
      this.uiArea = uiArea;
      this.options = options;
      this.value = this.options.value;
      this.$element = $("<div class=\"checkbox-control " + this.options["class"] + "\">\n  <span class=\"value " + (this.value ? 'true' : '') + "\"></span> <span class=\"name\">" + this.options.name + "</span>\n</div>");
      this.$value = this.$element.find('.value');
      this.options.$parent.append(this.$element);
      valueControl = new TopViewer.UIControl(this.uiArea, this.$element);
      valueControl.mousedown((function(_this) {
        return function(position) {
          return _this.setValue(!_this.value);
        };
      })(this));
    }

    CheckboxControl.prototype.setName = function(name) {
      return this.$element.find('.name').text(name);
    };

    CheckboxControl.prototype.setValue = function(value) {
      var base;
      this.value = value;
      if (value) {
        this.$value.addClass('true').removeClass('false');
      } else {
        this.$value.addClass('false').removeClass('true');
      }
      return typeof (base = this.options).onChange === "function" ? base.onChange(this.value, this) : void 0;
    };

    return CheckboxControl;

  })();

}).call(this);

//# sourceMappingURL=checkboxcontrol.js.map
