// Generated by CoffeeScript 1.10.0
(function() {
  TopViewer.DropdownControl = (function() {
    function DropdownControl(uiArea, options) {
      this.uiArea = uiArea;
      this.options = options;
      this.$element = $("<div class=\"dropdown-control " + this.options["class"] + "\">\n</div>");
      this.$values = $("<ul class='values'>");
      this.dropdownControl = new TopViewer.ToggleContainer(this.uiArea, {
        $parent: this.$element,
        text: this.options.text,
        visible: false,
        $contents: this.$values
      });
      this.options.$parent.append(this.$element);
      this.value = this.options.value;
      this.values = [];
      new TopViewer.UIControl(this.uiArea, this.$element);
    }

    DropdownControl.prototype.addValue = function(text, value) {
      var $item, control;
      $item = $("<li class='value'>" + text + "</li>");
      this.$values.append($item);
      control = new TopViewer.UIControl(this.uiArea, $item);
      control.click((function(_this) {
        return function() {
          _this.setValue(value);
          return _this.dropdownControl.toggleControl.setValue(false);
        };
      })(this));
      return this.values.push({
        value: value,
        text: text,
        $item: $item,
        control: control
      });
    };

    DropdownControl.prototype.setValue = function(newValue) {
      var value;
      this.value = newValue;
      value = _.find(this.values, function(value) {
        return value.value === newValue;
      });
      return this.dropdownControl.setText(value.text);
    };

    return DropdownControl;

  })();

}).call(this);

//# sourceMappingURL=dropdowncontrol.js.map
