// Generated by CoffeeScript 1.10.0
(function() {
  TopViewer.VertexColorsControl = (function() {
    function VertexColorsControl(uiArea, options) {
      this.uiArea = uiArea;
      this.options = options;
      this.value = this.options.value;
      this.$element = $("<div class='vertex-colors-control " + this.options["class"] + "'></div>");
      this.options.$parent.append(this.$element);
      this.typeControl = new TopViewer.DropdownControl(this.uiArea, {
        $parent: this.$element,
        "class": 'vertex-colors-type',
        onChange: (function(_this) {
          return function(value) {
            var $displayArea;
            _this.options.saveState.type = value;
            _this.$element.find('.sub-area').removeClass('displayed');
            switch (value) {
              case TopViewer.RenderingControls.VertexColorsType.Color:
                $displayArea = _this.$colorArea;
                break;
              case TopViewer.RenderingControls.VertexColorsType.Scalar:
                $displayArea = _this.$scalarArea;
            }
            return $displayArea.addClass('displayed');
          };
        })(this)
      });
      this.typeControl.addValue('Color', TopViewer.RenderingControls.VertexColorsType.Color);
      this.typeControl.addValue('Scalar', TopViewer.RenderingControls.VertexColorsType.Scalar);
      this.$colorArea = $("<div class='color-area sub-area'></div>");
      this.$element.append(this.$colorArea);
      this.colorControl = new TopViewer.ColorControl(this.uiArea, {
        $parent: this.$colorArea,
        saveState: this.options.saveState.color
      });
      this.$scalarArea = $("<div class='scalar-area sub-area'></div>");
      this.$element.append(this.$scalarArea);
      this.scalarControl = new TopViewer.ScalarControl(this.uiArea, {
        $parent: this.$scalarArea,
        saveState: this.options.saveState.scalar
      });
      this.typeControl.setValue(this.options.saveState.type);
    }

    return VertexColorsControl;

  })();

}).call(this);

//# sourceMappingURL=vertexcolorscontrol.js.map
